### ISSUE TITLE
Topic list programmatically generated

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-Schemas#28]
If all the device projects expose topic names as constants, then another simple java solution having all the device projects as dependencies can programmatically generate an output file used by the `install-radar-stack.sh` to update `.env`.

From a discussion with @blootsvoets 

> those jar could have a single command that simply lists topics, with flags like `--raw`, `--processed`, `--schemaless` to only list those topics so we can use them in different commands and `-0` to have them `'\0'`-separated. That could be a jar file, runnable like
```shell
$ java -jar schemas.jar topics --raw
android_empatica_e4_acceleration
android_empatica_e4_battery_level
android_empatica_e4_blood_volume_pulse
...
```

We may expose also a flag for each device, something like `--empatica` `--smartphone-sensor`.

Another idea is to provide more metadata in output. For instance, reusing `org.radarcns.avro.restapi.sensor.SensorType` a possible result may be
```shell
$ java -jar schemas.jar topics --raw
ACCELEROMETER: android_empatica_e4_acceleration
BATTERY: android_empatica_e4_battery_level
BLOOD_VOLUME_PULSE: android_empatica_e4_blood_volume_pulse
...
```
Then adding the flag `-q`, it will return only the topic list.
```shell
$ java -jar schemas.jar topics --raw -q
android_empatica_e4_acceleration
android_empatica_e4_battery_level
android_empatica_e4_blood_volume_pulse
...
```

**Comment by blootsvoets** [comment]
Done with #55
