### ISSUE TITLE
Folder layout

### ISSUE THREAD

**Issue by fnobilia** [RADAR-CNS/RADAR-Schemas#40]
After a discussion with @blootsvoets, we have identified the need to refactor the schema repository structure.

Instead of having a single `commons` root folder for all common schema, we can specialise it in `passive`, `active` and `kafka`.

`passive` folder will contain all schemas used by the passive sources. These schemas must have
 - `time` as first field, and it represents the `timestamp in UTC (s)` attached by the wearable device to the sample formatted in `double`
 - `timeReceived ` as second field, it represents the `timestamp in UTC (s)` attached by the smartphone when it receive the sample from the wearable device. It must be formatted in `double`

`active` folder will contain all schemas used by the active sources. These schemas must have
 - `time` as first field, formatted as `double`, it represents the `timestamp in UTC (s)` when the assessment has been submitted to the subject 
 - `timeCompleted ` as second field, , formatted as `double`, it represents the `timestamp in UTC (s)` when the subject has completed the assessment

`kafka` folder will contain all schemas internally used in Kafka.

The final tree folder structure will be:

- commons
  * active
  * kafka
  * passive
- rest

Having a common `time` field will simplify the logic in the `HDFS-Extractor` as well as it can provide a mechanism to compute temporal order across all collected data.

Unit tests should be provided to make sure schemas in each specific folder matches the requirements.

`README.md` should be updated to state the suggested schema layouts.

**Comment by blootsvoets** [comment]
An addition to the update and README: each folder for a passive or active source type should contain a `README.md` with links to the relevant hardware, specifications, developer information and RADAR implementation.

**Comment by fnobilia** [comment]
The folder tree can be augmented with a `specification` folder, again split in `passive` and `active`.

- commons
  * active
  * kafka
  * passive
- rest
- specification
  * active
  * passive

`specification/active` will contain `yml` files defining assessments. For example, the `phq_8.yml` file will state questions, possible answers and `RADAR tool` used to submit the question to the subject. 

`specification/passive` will contain `yml` files defining device specifications. The specification will list all on-board sensor. For each sensor there will be
- name
- sample rate
- unit
-`data_type` (define the sample is RAW data or it is the result of a vendor computation or a RADAR computation).

Other possible information at sensor level can be: kafka topic names and avro schemas.

A suitable starting point for the `active specification layout` is [here](https://github.com/RADAR-CNS/RADAR-Schemas/blob/phq8/questionnaire/specification/PHQ8_config.json).

A suitable starting point for the `passive specification layout` is [here](https://github.com/RADAR-CNS/RADAR-RestApi/blob/dev/src/integrationTest/resources/device-catalog.yml).

**Comment by fnobilia** [comment]
@blootsvoets I was thinking: we have three different kind of sources: `active`, `passive` and `monitor`. For `monitor` I mean `record_count` `uptime` and so on. We can modify the tree structure as follow
```
- commons
  * active
  * kafka
  * passive
  * monitor
- rest
- specification
  * active
  * passive
  * monitor
```

`Monitor` schemas will have only ` time` as timestamp field.

What do you think?

**Comment by blootsvoets** [comment]
Yes, that makes sense. I'm not entirely sure how we want to publish the Java classes (3 jars, for the top-level or 8 jars for the leaf level) Probably easiest to keep it as-is (3 jars).

**Comment by fnobilia** [comment]
I think 3 jar `commons`, `specification` and `rest`. I am happy to be in charge of this issue, if it is ok for you!

**Comment by blootsvoets** [comment]
Sure, I'm happy about that as well 👍
